/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import {
  Address,
  ExecutableScript,
  ExecuteScriptParams,
  ExecuteScriptResult,
  Script,
  SignerProvider,
  HexString,
} from "@alephium/web3";
import { default as WithdrawScriptJson } from "../Withdraw.ral.json";
import { default as DeployNewTokenScriptJson } from "../DeployNewToken.ral.json";

export const Withdraw = new ExecutableScript<{
  token: HexString;
  amount: bigint;
}>(Script.fromJson(WithdrawScriptJson));
export const DeployNewToken = new ExecutableScript<{
  templateId: HexString;
  name: HexString;
  symbol: HexString;
  decimals: bigint;
  initialSupply: bigint;
}>(Script.fromJson(DeployNewTokenScriptJson));
