/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import {
  Address,
  Contract,
  ContractState,
  TestContractResult,
  HexString,
  ContractFactory,
  EventSubscribeOptions,
  EventSubscription,
  CallContractParams,
  CallContractResult,
  TestContractParams,
  ContractEvent,
  subscribeContractEvent,
  subscribeContractEvents,
  testMethod,
  callMethod,
  multicallMethods,
  fetchContractState,
  Asset,
  ContractInstance,
  getContractEventsCurrentCount,
  TestContractParamsWithoutMaps,
  TestContractResultWithoutMaps,
  SignExecuteContractMethodParams,
  SignExecuteScriptTxResult,
  signExecuteMethod,
  addStdIdToFields,
  encodeContractFields,
  Narrow,
} from "@alephium/web3";
import { default as SimpleTokenContractJson } from "../SimpleToken.ral.json";
import { getContractByCodeHash, registerContract } from "./contracts";

// Custom types for the contract
export namespace SimpleTokenTypes {
  export type Fields = {
    symbol: HexString;
    name: HexString;
    decimals: bigint;
    supply: bigint;
    balance: bigint;
    owner: Address;
  };

  export type State = ContractState<Fields>;

  export type WithdrawEvent = ContractEvent<{ amount: bigint }>;

  export interface CallMethodTable {
    getSymbol: {
      params: Omit<CallContractParams<{}>, "args">;
      result: CallContractResult<HexString>;
    };
    getName: {
      params: Omit<CallContractParams<{}>, "args">;
      result: CallContractResult<HexString>;
    };
    getDecimals: {
      params: Omit<CallContractParams<{}>, "args">;
      result: CallContractResult<bigint>;
    };
    getTotalSupply: {
      params: Omit<CallContractParams<{}>, "args">;
      result: CallContractResult<bigint>;
    };
    balance: {
      params: Omit<CallContractParams<{}>, "args">;
      result: CallContractResult<bigint>;
    };
    withdraw: {
      params: CallContractParams<{ amount: bigint }>;
      result: CallContractResult<null>;
    };
  }
  export type CallMethodParams<T extends keyof CallMethodTable> =
    CallMethodTable[T]["params"];
  export type CallMethodResult<T extends keyof CallMethodTable> =
    CallMethodTable[T]["result"];
  export type MultiCallParams = Partial<{
    [Name in keyof CallMethodTable]: CallMethodTable[Name]["params"];
  }>;
  export type MultiCallResults<T extends MultiCallParams> = {
    [MaybeName in keyof T]: MaybeName extends keyof CallMethodTable
      ? CallMethodTable[MaybeName]["result"]
      : undefined;
  };
  export type MulticallReturnType<Callss extends MultiCallParams[]> = {
    [index in keyof Callss]: MultiCallResults<Callss[index]>;
  };

  export interface SignExecuteMethodTable {
    getSymbol: {
      params: Omit<SignExecuteContractMethodParams<{}>, "args">;
      result: SignExecuteScriptTxResult;
    };
    getName: {
      params: Omit<SignExecuteContractMethodParams<{}>, "args">;
      result: SignExecuteScriptTxResult;
    };
    getDecimals: {
      params: Omit<SignExecuteContractMethodParams<{}>, "args">;
      result: SignExecuteScriptTxResult;
    };
    getTotalSupply: {
      params: Omit<SignExecuteContractMethodParams<{}>, "args">;
      result: SignExecuteScriptTxResult;
    };
    balance: {
      params: Omit<SignExecuteContractMethodParams<{}>, "args">;
      result: SignExecuteScriptTxResult;
    };
    withdraw: {
      params: SignExecuteContractMethodParams<{ amount: bigint }>;
      result: SignExecuteScriptTxResult;
    };
  }
  export type SignExecuteMethodParams<T extends keyof SignExecuteMethodTable> =
    SignExecuteMethodTable[T]["params"];
  export type SignExecuteMethodResult<T extends keyof SignExecuteMethodTable> =
    SignExecuteMethodTable[T]["result"];
}

class Factory extends ContractFactory<
  SimpleTokenInstance,
  SimpleTokenTypes.Fields
> {
  encodeFields(fields: SimpleTokenTypes.Fields) {
    return encodeContractFields(
      addStdIdToFields(this.contract, fields),
      this.contract.fieldsSig,
      []
    );
  }

  eventIndex = { Withdraw: 0 };
  consts = {
    ErrorCodes: {
      InvalidOwner: BigInt("0"),
      InvalidWithdrawAmount: BigInt("1"),
    },
  };

  at(address: string): SimpleTokenInstance {
    return new SimpleTokenInstance(address);
  }

  tests = {
    getSymbol: async (
      params: Omit<
        TestContractParamsWithoutMaps<SimpleTokenTypes.Fields, never>,
        "args"
      >
    ): Promise<TestContractResultWithoutMaps<HexString>> => {
      return testMethod(this, "getSymbol", params, getContractByCodeHash);
    },
    getName: async (
      params: Omit<
        TestContractParamsWithoutMaps<SimpleTokenTypes.Fields, never>,
        "args"
      >
    ): Promise<TestContractResultWithoutMaps<HexString>> => {
      return testMethod(this, "getName", params, getContractByCodeHash);
    },
    getDecimals: async (
      params: Omit<
        TestContractParamsWithoutMaps<SimpleTokenTypes.Fields, never>,
        "args"
      >
    ): Promise<TestContractResultWithoutMaps<bigint>> => {
      return testMethod(this, "getDecimals", params, getContractByCodeHash);
    },
    getTotalSupply: async (
      params: Omit<
        TestContractParamsWithoutMaps<SimpleTokenTypes.Fields, never>,
        "args"
      >
    ): Promise<TestContractResultWithoutMaps<bigint>> => {
      return testMethod(this, "getTotalSupply", params, getContractByCodeHash);
    },
    balance: async (
      params: Omit<
        TestContractParamsWithoutMaps<SimpleTokenTypes.Fields, never>,
        "args"
      >
    ): Promise<TestContractResultWithoutMaps<bigint>> => {
      return testMethod(this, "balance", params, getContractByCodeHash);
    },
    withdraw: async (
      params: TestContractParamsWithoutMaps<
        SimpleTokenTypes.Fields,
        { amount: bigint }
      >
    ): Promise<TestContractResultWithoutMaps<null>> => {
      return testMethod(this, "withdraw", params, getContractByCodeHash);
    },
  };

  stateForTest(
    initFields: SimpleTokenTypes.Fields,
    asset?: Asset,
    address?: string
  ) {
    return this.stateForTest_(initFields, asset, address, undefined);
  }
}

// Use this object to test and deploy the contract
export const SimpleToken = new Factory(
  Contract.fromJson(
    SimpleTokenContractJson,
    "",
    "33cc064ef0e8efe76bf2d40a68e1caff81046c690309a11bbb06c28a2ba9fcfc",
    []
  )
);
registerContract(SimpleToken);

// Use this class to interact with the blockchain
export class SimpleTokenInstance extends ContractInstance {
  constructor(address: Address) {
    super(address);
  }

  async fetchState(): Promise<SimpleTokenTypes.State> {
    return fetchContractState(SimpleToken, this);
  }

  async getContractEventsCurrentCount(): Promise<number> {
    return getContractEventsCurrentCount(this.address);
  }

  subscribeWithdrawEvent(
    options: EventSubscribeOptions<SimpleTokenTypes.WithdrawEvent>,
    fromCount?: number
  ): EventSubscription {
    return subscribeContractEvent(
      SimpleToken.contract,
      this,
      options,
      "Withdraw",
      fromCount
    );
  }

  view = {
    getSymbol: async (
      params?: SimpleTokenTypes.CallMethodParams<"getSymbol">
    ): Promise<SimpleTokenTypes.CallMethodResult<"getSymbol">> => {
      return callMethod(
        SimpleToken,
        this,
        "getSymbol",
        params === undefined ? {} : params,
        getContractByCodeHash
      );
    },
    getName: async (
      params?: SimpleTokenTypes.CallMethodParams<"getName">
    ): Promise<SimpleTokenTypes.CallMethodResult<"getName">> => {
      return callMethod(
        SimpleToken,
        this,
        "getName",
        params === undefined ? {} : params,
        getContractByCodeHash
      );
    },
    getDecimals: async (
      params?: SimpleTokenTypes.CallMethodParams<"getDecimals">
    ): Promise<SimpleTokenTypes.CallMethodResult<"getDecimals">> => {
      return callMethod(
        SimpleToken,
        this,
        "getDecimals",
        params === undefined ? {} : params,
        getContractByCodeHash
      );
    },
    getTotalSupply: async (
      params?: SimpleTokenTypes.CallMethodParams<"getTotalSupply">
    ): Promise<SimpleTokenTypes.CallMethodResult<"getTotalSupply">> => {
      return callMethod(
        SimpleToken,
        this,
        "getTotalSupply",
        params === undefined ? {} : params,
        getContractByCodeHash
      );
    },
    balance: async (
      params?: SimpleTokenTypes.CallMethodParams<"balance">
    ): Promise<SimpleTokenTypes.CallMethodResult<"balance">> => {
      return callMethod(
        SimpleToken,
        this,
        "balance",
        params === undefined ? {} : params,
        getContractByCodeHash
      );
    },
    withdraw: async (
      params: SimpleTokenTypes.CallMethodParams<"withdraw">
    ): Promise<SimpleTokenTypes.CallMethodResult<"withdraw">> => {
      return callMethod(
        SimpleToken,
        this,
        "withdraw",
        params,
        getContractByCodeHash
      );
    },
  };

  transact = {
    getSymbol: async (
      params: SimpleTokenTypes.SignExecuteMethodParams<"getSymbol">
    ): Promise<SimpleTokenTypes.SignExecuteMethodResult<"getSymbol">> => {
      return signExecuteMethod(SimpleToken, this, "getSymbol", params);
    },
    getName: async (
      params: SimpleTokenTypes.SignExecuteMethodParams<"getName">
    ): Promise<SimpleTokenTypes.SignExecuteMethodResult<"getName">> => {
      return signExecuteMethod(SimpleToken, this, "getName", params);
    },
    getDecimals: async (
      params: SimpleTokenTypes.SignExecuteMethodParams<"getDecimals">
    ): Promise<SimpleTokenTypes.SignExecuteMethodResult<"getDecimals">> => {
      return signExecuteMethod(SimpleToken, this, "getDecimals", params);
    },
    getTotalSupply: async (
      params: SimpleTokenTypes.SignExecuteMethodParams<"getTotalSupply">
    ): Promise<SimpleTokenTypes.SignExecuteMethodResult<"getTotalSupply">> => {
      return signExecuteMethod(SimpleToken, this, "getTotalSupply", params);
    },
    balance: async (
      params: SimpleTokenTypes.SignExecuteMethodParams<"balance">
    ): Promise<SimpleTokenTypes.SignExecuteMethodResult<"balance">> => {
      return signExecuteMethod(SimpleToken, this, "balance", params);
    },
    withdraw: async (
      params: SimpleTokenTypes.SignExecuteMethodParams<"withdraw">
    ): Promise<SimpleTokenTypes.SignExecuteMethodResult<"withdraw">> => {
      return signExecuteMethod(SimpleToken, this, "withdraw", params);
    },
  };

  async multicall<Calls extends SimpleTokenTypes.MultiCallParams>(
    calls: Calls
  ): Promise<SimpleTokenTypes.MultiCallResults<Calls>>;
  async multicall<Callss extends SimpleTokenTypes.MultiCallParams[]>(
    callss: Narrow<Callss>
  ): Promise<SimpleTokenTypes.MulticallReturnType<Callss>>;
  async multicall<
    Callss extends
      | SimpleTokenTypes.MultiCallParams
      | SimpleTokenTypes.MultiCallParams[]
  >(callss: Callss): Promise<unknown> {
    return await multicallMethods(
      SimpleToken,
      this,
      callss,
      getContractByCodeHash
    );
  }
}
